import pandas as pd
import numpy as np

def create_features(df, lag_horizon=14):
    """
    Creates time-series features avoiding data leakage.
    Since we want to predict up to `lag_horizon` days into the future,
    all historical features (lags, rolling stats) must be shifted by at least `lag_horizon`.
    """
    df = df.copy()
    
    # 1. Temporal Features
    df['day_of_week'] = df['date'].dt.dayofweek
    df['month'] = df['date'].dt.month
    df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)
    
    # We will sort by store, item, and date to ensure proper lag calculation
    df = df.sort_values(['store_id', 'item_id', 'date'])
    
    # Group by store and item for time-series features
    grouped = df.groupby(['store_id', 'item_id'])
    
    # 2. Lag Features
    # The minimum lag is `lag_horizon` (e.g., 14 days)
    lags = [lag_horizon, lag_horizon + 7, lag_horizon + 14, lag_horizon + 28]
    for lag in lags:
        df[f'sales_lag_{lag}'] = grouped['sales'].shift(lag)
        
    # 3. Rolling Window Statistics
    # Based on the first available lag (t - lag_horizon)
    windows = [7, 14, 28]
    for window in windows:
        # We compute rolling mean on the shifted series to avoid leakage
        shifted_sales = grouped['sales'].shift(lag_horizon)
        df[f'sales_rolling_mean_{window}'] = shifted_sales.rolling(window).mean()
        df[f'sales_rolling_std_{window}'] = shifted_sales.rolling(window).std()

    # Drop rows with NaN values generated by lagging
    # This means the first `lag_horizon + max_window` days per item will be dropped
    max_lag = lag_horizon + max(windows)
    df = df.dropna().reset_index(drop=True)
    
    # Encode categorical features
    df['category'] = df['category'].astype('category')
    
    return df

def split_data(df, validation_days=28, test_days=14):
    """
    Splits the data chronologically into train, validation, and test sets.
    """
    max_date = df['date'].max()
    test_start = max_date - pd.Timedelta(days=test_days - 1)
    val_start = test_start - pd.Timedelta(days=validation_days)
    
    train = df[df['date'] < val_start].copy()
    val = df[(df['date'] >= val_start) & (df['date'] < test_start)].copy()
    test = df[df['date'] >= test_start].copy()
    
    return train, val, test
